# Generated by Django 5.2.5 on 2025-09-01 23:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e6fde150-c0e6-48a1-94ac-d156063edb46'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('61528fdc-be8e-486c-a5bf-418ee44dae89'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('zip', models.FileField(upload_to='')),
                ('entrypoint', models.CharField()),
                ('tipo', models.CharField(choices=[('robot', 'robot'), ('python', 'python')], default='robot', max_length=6)),
                ('diretorio', models.CharField()),
                ('log_timeout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('94c21d64-ed72-4338-be71-c5e459c03dc1'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator])),
                ('senha', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='LogRobot',
            fields=[
                ('id', models.CharField(default=uuid.UUID('96868983-0d0c-4bbd-bc80-211b305009fb'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_hora', models.DateField(default=django.utils.timezone.now)),
                ('tasks_falhas', models.IntegerField()),
                ('tasks_completas', models.IntegerField()),
                ('tasks_puladas', models.IntegerField()),
                ('duracao', models.IntegerField()),
                ('link', models.CharField()),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
                ('id_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.bot')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario'),
        ),
        migrations.AddField(
            model_name='automacao',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario'),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.CharField(default=uuid.UUID('756cca8f-c0c2-4844-ad68-5b8e8d7bed21'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('cron', models.CharField(max_length=40)),
                ('ativo', models.BooleanField()),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PassoAutomacao',
            fields=[
                ('ordem', models.IntegerField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.UUID('4f2b1837-e52b-4905-983b-634648b05ecd'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
                ('id_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orchestrator.bot')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_automacao', 'ordem'), name='unique_id_ordem_passo')],
            },
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('id', 'nome'), name='unique_id_nome_bot'),
        ),
        migrations.AddConstraint(
            model_name='automacao',
            constraint=models.UniqueConstraint(fields=('id', 'nome'), name='unique_id_nome_automacao'),
        ),
    ]
