# Generated by Django 5.2.5 on 2025-09-02 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7d6d1427-c079-4c7a-a6c0-15bb4d2c83ef'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=800)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.CharField(default=uuid.UUID('9b7d7ff9-9b79-4bbf-b434-68f82d20eccb'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('cron', models.CharField(max_length=40)),
                ('ativo', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('194b2ca6-678d-4191-aeaf-9d339b4e5156'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('zip', models.FileField(upload_to='')),
                ('entrypoint', models.CharField()),
                ('tipo', models.CharField(choices=[('robot', 'robot'), ('python', 'python')], default='robot', max_length=6)),
                ('diretorio', models.CharField(default='abc')),
                ('log_timeout', models.IntegerField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRobot',
            fields=[
                ('id', models.CharField(default=uuid.UUID('51a60715-4d9f-40e2-ab01-b5080c54b3bf'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_hora', models.DateField(default=django.utils.timezone.now)),
                ('tasks_falhas', models.IntegerField()),
                ('tasks_completas', models.IntegerField()),
                ('tasks_puladas', models.IntegerField()),
                ('duracao', models.IntegerField()),
                ('link', models.CharField()),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
                ('id_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.bot')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PassoAutomacao',
            fields=[
                ('ordem', models.IntegerField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.UUID('62d6760b-692c-4b60-b6a0-014c95509ac1'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_automacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.automacao')),
                ('id_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='orchestrator.bot')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='automacao',
            constraint=models.UniqueConstraint(fields=('id', 'nome'), name='unique_id_nome_automacao'),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('id', 'nome'), name='unique_id_nome_bot'),
        ),
        migrations.AddConstraint(
            model_name='passoautomacao',
            constraint=models.UniqueConstraint(fields=('id_automacao', 'ordem'), name='unique_id_ordem_passo'),
        ),
    ]
