# Generated by Django 5.2.5 on 2025-09-01 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('ab242519-87f9-4ffe-9fd2-b33091b9f36c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d409f780-4581-4f56-85c3-b3c642f55095'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='diretorio',
            field=models.CharField(default='abc'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd4e6eaa-52e1-4852-ada3-fe293473de50'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.usuario'),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('515aa030-dd51-40ee-95e1-c7113c4b60bb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7552a22f-78da-458e-b0c0-200094807c6d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('75f494df-0b31-4693-98ba-4e3be677667d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
