# Generated by Django 5.2.5 on 2025-09-02 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('ee038b45-ea75-4d5a-accf-f12f98347022'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5491c890-1948-425d-87c9-b75072edc29f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aaeb3e1b-af26-4009-bed2-a47b3b6ece4d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='zip',
            field=models.FileField(upload_to='C:/tmp'),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('ebeb4a70-e24d-4bd2-ae5c-69c393a18743'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf630c46-de09-4303-a0dc-f2eb83653474'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
