# Generated by Django 5.2.5 on 2025-09-02 00:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_alter_agendamento_id_alter_automacao_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('65335aa1-75b1-4eec-b9a3-307a81c1e070'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b95d2907-608b-4696-ad76-f8bc5a08169c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a8ae5fa-6f34-41bb-9a95-82e412a5e6af'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('2eddc0e0-34e9-4446-b0d0-1b04faaac242'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8810eee9-5ed4-48be-a73c-8ad12b41fcc3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('347ce037-7af5-4b12-a75b-2618022ebc71'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
