# Generated by Django 5.2.5 on 2025-09-02 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('9933742d-6d5b-476c-9c51-571e14c3b5c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d785912a-170f-4cd4-b17b-64226b7dcb83'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48e83fe2-7812-4560-ba36-b8293783bca4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('c6c1fe13-d030-4ff9-851f-4cfda0cf2faf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a3055d30-19c1-4f24-8cb6-6153d695b68b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
