# Generated by Django 5.2.5 on 2025-09-02 16:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('9dfe90e5-acfd-4e3b-9aef-61828980341f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b61f09ef-6735-4e04-b572-1fda00293a33'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6739b392-6fe9-46e3-81c1-8d8dc36ce4fc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='zip',
            field=models.FileField(upload_to='bots_zip/'),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('62715718-68ed-4f65-ae96-93b42dda6242'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('02736fb5-6a2c-4e2f-9aed-b56fb66b2143'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
