# Generated by Django 5.2.5 on 2025-09-02 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('0dc528ff-08ac-483e-8922-6cb3d9c2ab3b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ff6e12cb-f1bc-42af-8b0f-be4602a0ce19'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0adb3f03-7994-47db-a98c-97be1bcd99e5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('75343873-0a73-44cf-817e-642c8b3cd133'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7adeaec-a430-4fb7-ac2f-82b61a902cdd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
