# Generated by Django 5.2.5 on 2025-09-02 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('51741c08-7ac2-4a1f-813a-bd72ff933f55'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cb7571d6-cf8f-4cf6-b90e-c5d31c25bf22'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be482532-01c7-4faf-9912-e538a9ce84e1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('5c4457b5-4f89-4879-bd32-b1d36381bd1a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1c7c184b-a6c9-4220-9005-1658097a55df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
