# Generated by Django 5.2.5 on 2025-09-03 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0012_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('52eb6f75-db27-43b8-852d-d5454934a577'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e5e276a-9fe1-463a-8316-181a6064d7b5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d02c0a10-0372-4ae2-bae9-c782939e0a1b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('53a4d3ab-2b53-42f3-b1b3-f3a61f34240e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('54ce2657-2161-4413-8bef-da3fadf73ba4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
