# Generated by Django 5.2.5 on 2025-09-03 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0013_alter_agendamento_id_alter_automacao_id_alter_bot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.CharField(default=uuid.UUID('8a21e40a-aa84-410d-97df-54254208ad97'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e41d1ec8-e7f1-4e68-8f5a-15eaaec90048'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f1ae3b63-af8b-4d95-9e80-bd72cf94ca80'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logrobot',
            name='id',
            field=models.CharField(default=uuid.UUID('675ccfd4-5a61-4e58-9328-31ddeee32132'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passoautomacao',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7066a3c9-a74f-49a0-9cfb-b8784dd0da84'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
